---
- hosts: kubernetes
  user: root

  tasks:
    - name: deploy reapp on kuberbetes
      command: kubectl apply -f regapp-deployment.yml

    - name : vreate service for regapp
      command: kubectl apply -f regapp-service.yml

    - name: update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.apps/valaxy-regapp
